# Generated by Django 4.1.3 on 2022-12-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poe_store_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(max_length=200)),
                ('baseType', models.CharField(max_length=200)),
                ('inventoryId', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=200)),
                ('stackSize', models.IntegerField(default=1)),
                ('note', models.CharField(default='Contact for price', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
