# Generated by Django 4.1.3 on 2022-12-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poe_store_app', '0002_currency_league'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(max_length=200)),
                ('baseType', models.CharField(max_length=200)),
                ('inventoryId', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='currency',
            name='icon',
            field=models.CharField(max_length=1000),
        ),
    ]
