# Generated by Django 4.1.3 on 2022-12-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poe_store_app', '0010_gear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='explicitMods',
            field=models.CharField(default='None', max_length=1000),
        ),
        migrations.AlterField(
            model_name='gear',
            name='impliicitMods',
            field=models.CharField(default='None', max_length=1000),
        ),
    ]
