# Generated by Django 4.1.3 on 2022-12-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poe_store_app', '0011_alter_gear_explicitmods_alter_gear_impliicitmods'),
    ]

    operations = [
        migrations.AddField(
            model_name='blight',
            name='name',
            field=models.CharField(default='Name', max_length=200),
        ),
        migrations.AddField(
            model_name='currency',
            name='name',
            field=models.CharField(default='Name', max_length=200),
        ),
        migrations.AddField(
            model_name='delirium',
            name='name',
            field=models.CharField(default='Name', max_length=200),
        ),
        migrations.AddField(
            model_name='delve',
            name='name',
            field=models.CharField(default='Name', max_length=200),
        ),
        migrations.AddField(
            model_name='divination',
            name='name',
            field=models.CharField(default='Name', max_length=200),
        ),
        migrations.AddField(
            model_name='essence',
            name='name',
            field=models.CharField(default='Name', max_length=200),
        ),
        migrations.AddField(
            model_name='fragment',
            name='name',
            field=models.CharField(default='Name', max_length=200),
        ),
        migrations.AddField(
            model_name='gear',
            name='name',
            field=models.CharField(default='Name', max_length=200),
        ),
        migrations.AddField(
            model_name='gems',
            name='name',
            field=models.CharField(default='Name', max_length=200),
        ),
    ]
