# Generated by Django 4.1.3 on 2022-12-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poe_store_app', '0012_blight_name_currency_name_delirium_name_delve_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='explicitMods',
            field=models.CharField(default='None', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='gear',
            name='impliicitMods',
            field=models.CharField(default='None', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='gear',
            name='note',
            field=models.CharField(default='Contact for price', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gear',
            name='stackSize',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
