# Generated by Django 4.1.3 on 2022-12-20 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poe_store_app', '0013_alter_gear_explicitmods_alter_gear_impliicitmods_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gear',
            old_name='impliicitMods',
            new_name='implicitMods',
        ),
    ]
