# Generated by Django 4.1.3 on 2022-12-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poe_store_app', '0015_blight_category_currency_category_delirium_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blight',
            name='explicitMods',
            field=models.CharField(default='None', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='blight',
            name='implicitMods',
            field=models.CharField(default='None', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='explicitMods',
            field=models.CharField(default='None', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='implicitMods',
            field=models.CharField(default='None', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='delirium',
            name='explicitMods',
            field=models.CharField(default='None', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='delirium',
            name='implicitMods',
            field=models.CharField(default='None', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='delve',
            name='explicitMods',
            field=models.CharField(default='None', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='delve',
            name='implicitMods',
            field=models.CharField(default='None', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='divination',
            name='explicitMods',
            field=models.CharField(default='None', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='divination',
            name='implicitMods',
            field=models.CharField(default='None', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='essence',
            name='explicitMods',
            field=models.CharField(default='None', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='essence',
            name='implicitMods',
            field=models.CharField(default='None', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='fragment',
            name='explicitMods',
            field=models.CharField(default='None', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='fragment',
            name='implicitMods',
            field=models.CharField(default='None', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='gems',
            name='explicitMods',
            field=models.CharField(default='None', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='gems',
            name='implicitMods',
            field=models.CharField(default='None', max_length=1000, null=True),
        ),
    ]
