# Generated by Django 4.1.3 on 2022-12-24 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poe_store_app', '0018_alter_blight_stacksize_alter_currency_stacksize_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Gear', max_length=200)),
                ('league', models.CharField(max_length=200)),
                ('name', models.CharField(default='Name', max_length=200)),
                ('baseType', models.CharField(max_length=200)),
                ('inventoryId', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=1000)),
                ('explicitMods', models.CharField(default='None', max_length=1000, null=True)),
                ('implicitMods', models.CharField(default='None', max_length=1000, null=True)),
                ('stackSize', models.IntegerField(default=1, null=True)),
                ('note', models.CharField(default='Contact for price', max_length=200, null=True)),
            ],
        ),
    ]
