# Generated by Django 4.1.3 on 2022-12-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poe_store_app', '0020_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='item_id',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
